--- #YAML:1.0
 name: Apache-Sling
 abstract: Perl interface to Apache SLing Web Framework
 version: 0.04
 author:
   - Daniel Parry <perl@ddp.me.uk>
 license: perl
 distribution_type: module
 requires:
   Fcntl: 0
   HTTP::Request::Common: 0
   LWP::UserAgent: 0
   MIME::Base64: 0
   Text::CSV: 0
 build_requires:
   Test: 0
 urls:
   license: http://dev.perl.org/licenses/
